new_sample/new_sample/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("zaiko.urls")),
    path('zaiko2/',include("zaiko2.urls")),
]

new_sample/zaiko/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index,shouhin_all,csv_imp,csv_imp_page,dele,hinban_enter_ajax,hinban_click_ajax,color_size_click_ajax,\
                    kakou_click_ajax,swatch_click_ajax,keep_kaijo_ajax,check_addlist_ajax,irai_del_ajax,irai_num_copy,\
                    hinban_click_ajax2,color_size_click_ajax2,toriyose_add_ajax,last_kakunin,\
                    haisou_cus_success,haisou_tempo_success,haisou_keep_success,irai_success,irai_rireki,irai_shusei_ajax,irai_shusei_index,irai_shusei,\
                    rireki_kakunin,page_prev,page_first,page_next,page_last,rireki_kensaku,rireki_kensaku_all,cancel_ajax,keep_hassou,\
                    csv_make,csv_download,unsou_page,unsou_csv_imp,all_delete,eigyou_csv_download


app_name="zaiko"
urlpatterns = [
    path('', index, name="index"),
    path('login/', auth_views.LoginView.as_view(template_name='zaiko/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('shouhin_all/', shouhin_all, name="shouhin_all"), 
    path('irai_success/', irai_success, name="irai_success"), 
    path('irai_rireki/', irai_rireki, name="irai_rireki"), 
    path('irai_shusei_ajax/', irai_shusei_ajax, name="irai_shusei_ajax"), 
    path('irai_shusei_index/', irai_shusei_index, name="irai_shusei_index"), 
    path('irai_shusei/', irai_shusei, name="irai_shusei"), 
    path('rireki_kensaku/', rireki_kensaku, name="rireki_kensaku"),
    path('rireki_kensaku_all/', rireki_kensaku_all, name="rireki_kensaku_all"), 
    path('page_prev/', page_prev, name="page_prev"), 
    path('page_first/', page_first, name="page_first"),
    path('page_next/', page_next, name="page_next"), 
    path('page_last/', page_last, name="page_last"), 
    path('csv_imp_page/', csv_imp_page, name="csv_imp_page"), 
    path('csv_imp/', csv_imp, name="csv_imp"),
    path('dele/', dele, name="dele"), 
    path('hinban_enter_ajax/', hinban_enter_ajax, name="hinban_enter_ajax"),
    path('hinban_click_ajax/', hinban_click_ajax, name="hinban_click_ajax"),
    path('color_size_click_ajax/', color_size_click_ajax, name="color_size_click_ajax"),
    path('kakou_click_ajax/', kakou_click_ajax, name="kakou_click_ajax"),
    path('swatch_click_ajax/', swatch_click_ajax, name="swatch_click_ajax"),
    path('keep_kaijo_ajax/', keep_kaijo_ajax, name="keep_kaijo_ajax"),
    path('check_addlist_ajax/', check_addlist_ajax, name="check_addlist_ajax"),
    path('irai_del_ajax/', irai_del_ajax, name="irai_del_ajax"),
    path('irai_num_copy/', irai_num_copy, name="irai_num_copy"),
    path('hinban_click_ajax2/', hinban_click_ajax2, name="hinban_click_ajax2"),
    path('color_size_click_ajax2/', color_size_click_ajax2, name="color_size_click_ajax2"),
    path('toriyose_add_ajax/', toriyose_add_ajax, name="toriyose_add_ajax"),
    path('last_kakunin/', last_kakunin, name="last_kakunin"),
    path('haisou_cus_success/', haisou_cus_success, name="haisou_cus_success"),
    path('haisou_tempo_success/', haisou_tempo_success, name="haisou_tempo_success"),
    path('haisou_keep_success/', haisou_keep_success, name="haisou_keep_success"),
    path('rireki_kakunin/<int:pk>', rireki_kakunin, name="rireki_kakunin"),
    path('cancel_ajax/', cancel_ajax, name="cancel_ajax"),
    path('keep_hassou/', keep_hassou, name="keep_hassou"),
    path('csv_make/', csv_make, name="csv_make"),
    path('csv_download/', csv_download, name="csv_download"),
    path('unsou_page/', unsou_page, name="unsou_page"),
    path('unsou_csv_imp/', unsou_csv_imp, name="unsou_csv_imp"),
    path('all_delete/', all_delete, name="all_delete"),
    path('eigyou_csv_download/', eigyou_csv_download, name="eigyou_csv_download")
]

new_sample/zaiko2/urls.py
from django.urls import path
from .views import index2,category_click_ajax,hinban_click_ajax,list_click_ajax,ikkatsu_hinban,ikkatsu_del,sample_num_auto,\
                    kobetsu_del,kobetsu_up,label_add,label_print,label_del,henkyaku,henkyaku_kensaku,henkyaku_del,henkyaku_all,henkyaku_csv,henkyaku_spread,\
                    size_category,size_num,size_name,size_new,category_num,category_name,category_new,shouhin_csv_download

app_name="zaiko2"
urlpatterns = [
    path('index2/', index2, name="index2"),
    path('category_click_ajax/', category_click_ajax, name="category_click_ajax"),
    path('hinban_click_ajax/', hinban_click_ajax, name="hinban_click_ajax"),
    path('list_click_ajax/', list_click_ajax, name="list_click_ajax"),
    path('ikkatsu_hinban/', ikkatsu_hinban, name="ikkatsu_hinban"),
    path('ikkatsu_del/', ikkatsu_del, name="ikkatsu_del"),
    path('sample_num_auto/', sample_num_auto, name="sample_num_auto"),
    path('kobetsu_del/', kobetsu_del, name="kobetsu_del"),
    path('kobetsu_up/', kobetsu_up, name="kobetsu_up"),
    path('label_add/', label_add, name="label_add"),
    path('label_print/', label_print, name="label_print"),
    path('label_del/', label_del, name="label_del"),
    path('henkyaku/', henkyaku, name="henkyaku"),
    path('henkyaku_kensaku/', henkyaku_kensaku, name="henkyaku_kensaku"),
    path('henkyaku_del/', henkyaku_del, name="henkyaku_del"),
    path('henkyaku_all/', henkyaku_all, name="henkyaku_all"),
    path('henkyaku_csv/', henkyaku_csv, name="henkyaku_csv"),
    path('henkyaku_spread/', henkyaku_spread, name="henkyaku_spread"),
    path('size_category/', size_category, name="size_category"),
    path('size_num/', size_num, name="size_num"),
    path('size_name/', size_name, name="size_name"),
    path('size_new/', size_new, name="size_new"),
    path('category_num/', category_num, name="category_num"),
    path('category_name/', category_name, name="category_name"),
    path('category_new/', category_new, name="category_new"),
    path('shouhin_csv_download/', shouhin_csv_download, name="shouhin_csv_download"),
]

new_sample/zaiko/views.py
from django.shortcuts import render,redirect
from .models import Shouhin,Rental,Size,Shozoku,Rireki_rental,Rireki_shouhin,Category
from django.contrib.auth.decorators import login_required
import io
import csv
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json
from django.db.models import Max
import datetime
from django.db.models import Q
import urllib.parse



@login_required
def index(request):
    if "sample" not in request.session:
        request.session["sample"]=[]
    if "hinban" not in request.session:
        request.session["hinban"]=[]
    if "color" not in request.session:
        request.session["color"]=[]
    if "size" not in request.session:
        request.session["size"]=[]
    if "page_num" not in request.session:
        request.session["page_num"]=1
    if "all_page_num" not in request.session:
        request.session["all_page_num"]=""
    if "kensaku" not in request.session:
        request.session["kensaku"]={}
    if "irai_num" not in request.session["kensaku"]:
        request.session["kensaku"]["irai_num"]=""
    if "rental_day_st" not in request.session["kensaku"]:
        request.session["kensaku"]["rental_day_st"]=""
    if "rental_day_ed" not in request.session["kensaku"]:
        request.session["kensaku"]["rental_day_ed"]=""
    if "irai_type" not in request.session["kensaku"]:
        request.session["kensaku"]["irai_type"]=""
    if "status" not in request.session["kensaku"]:
        request.session["kensaku"]["status"]=""
    if "tel" not in request.session["kensaku"]:
        request.session["kensaku"]["tel"]=""
    if "tantou" not in request.session["kensaku"]:
        request.session["kensaku"]["tantou"]=""
    if "nouhin_com" not in request.session["kensaku"]:
        request.session["kensaku"]["nouhin_com"]=""
    if "nouhin_cus" not in request.session["kensaku"]:
        request.session["kensaku"]["nouhin_cus"]=""
    if "mail" not in request.session["kensaku"]:
        request.session["kensaku"]["mail"]=""
    if "success_num" not in request.session:
        request.session["success_num"]=""
    if "csv_list" not in request.session:
        request.session["csv_list"]=""
    if "comment" not in request.session:
        request.session["comment"]=""
    if "shusei_num" not in request.session:
        request.session["shusei_num"]=""
    if "shusei_pk" not in request.session:
        request.session["shusei_pk"]=""

    request.session["comment"]="" # zaiko2:index2 の制御

    # キープ解除
    items=Shouhin.objects.filter(joutai=2)
    for item_s in items:
        item_r=Rental.objects.get(irai_num_rental=item_s.irai_num)
        day=datetime.date.today() - item_r.rental_day
        if day.days > 14:
            item_s.joutai=0
            moto_num=item_s.irai_num
            item_s.irai_num=0
            item_s.save()
            if Shouhin.objects.filter(irai_num=moto_num).count()==0:
                Rental.objects.get(irai_num_rental=moto_num).delete()

    # 依頼商品一覧
    irai_shouhin_list=list(request.session["sample"])
    data=[]
    for i in irai_shouhin_list:
        data2={}
        shouhin=Shouhin.objects.get(hontai_num=i)
        data2["hontai_num"]=shouhin.hontai_num
        data2["sample_num"]=shouhin.sample_num
        data2["shouhin_num"]=shouhin.shouhin_num
        data2["brand"]=shouhin.brand
        data2["shouhin_name"]=shouhin.shouhin_name
        data2["color"]=shouhin.color
        data2["size"]=shouhin.size
        if shouhin.sample_num=="":
            data2["kubun"]="取り寄せ"
        else:
            data2["kubun"]="在庫"
        data.append(data2)
    kazu=len(data)
    size_list=Size.objects.all().order_by("size_num")
    shozoku_list=Shozoku.objects.all()
    today=datetime.date.today().strftime("%Y-%m-%d")
    kigen=(datetime.date.today() + datetime.timedelta(days=14)).strftime("%Y-%m-%d")
    
    #user認証
    kanri=0
    if request.user.username == "p1masao":
        kanri=1

    params={
        "irai_shouhin_list":data,
        "kazu":kazu,
        "size_list":size_list,
        "shozoku_list":shozoku_list,
        "today":today,
        "kigen":kigen,
        "kanri":kanri,
    }
    return render(request,"zaiko/index.html",params)


def shouhin_all(request):
    return render(request,"zaiko/shouhin_all.html")


@login_required
def irai_rireki(request):
    irai_num=request.session["kensaku"]["irai_num"]
    rental_day_st=request.session["kensaku"]["rental_day_st"]
    rental_day_ed=request.session["kensaku"]["rental_day_ed"]
    irai_type=request.session["kensaku"]["irai_type"]
    tantou=request.session["kensaku"]["tantou"]
    nouhin_com=request.session["kensaku"]["nouhin_com"]
    nouhin_cus=request.session["kensaku"]["nouhin_cus"]
    status=request.session["kensaku"]["status"]
    tel=request.session["kensaku"]["tel"]
    mail=request.session["kensaku"]["mail"]
    
    request.session["comment"]="" # zaiko2:index2 の制御

    #検索条件
    str={}
    if irai_num != "":
        str["irai_num"]=irai_num
    if rental_day_st != "":
        str["rental_day__gte"]=rental_day_st
    if rental_day_ed != "":
        str["rental_day__lte"]=rental_day_ed
    if irai_type != "":
        str["irai_type"]=irai_type
    if tantou != "":
        str["tantou__contains"]=tantou
    if nouhin_com != "":
        str["nouhin_com__contains"]=nouhin_com
    if nouhin_cus != "":
        str["nouhin_cus__contains"]=nouhin_cus
    if status != "":
        str["status"]=status
    if tel != "":
        str["haisou_tel_kensaku"]=tel.replace("-","")
    if mail != "":
        str["haisou_mail"]=mail
        

    items=Rireki_rental.objects.filter(**str).order_by("irai_num").reverse()
    shozoku_list=Shozoku.objects.all()
    #全ページ数
    if items.count()==0:
        all_num=1
    elif items.count() % 30== 0:
        all_num=items.count() / 30
    else:
        all_num=items.count() // 30 + 1
    all_num=int(all_num)
    request.session["all_page_num"]=all_num
    num=request.session["page_num"]
    items=items[(num-1)*30 : num*30]

    #user認証
    kanri=0
    if request.user.username == "p1masao":
        kanri=1

    params={
        "items":items,
        "shozoku_list":shozoku_list,
        "num":num,
        "all_num":all_num,
        "kanri":kanri,
    }
    return render(request,"zaiko/rireki.html",params)


def rireki_kensaku(request):
    irai_num=request.POST["irai_num"]
    rental_day_st=request.POST["rental_day_st"]
    rental_day_ed=request.POST["rental_day_ed"]
    irai_type=request.POST["irai_type"]
    tantou=request.POST["tantou"]
    nouhin_com=request.POST["nouhin_com"]
    nouhin_cus=request.POST["nouhin_cus"]
    status=request.POST["status"]
    tel=request.POST["tel"]
    mail=request.POST["mail"]

    request.session["kensaku"]["irai_num"]=irai_num
    request.session["kensaku"]["rental_day_st"]=rental_day_st
    request.session["kensaku"]["rental_day_ed"]=rental_day_ed
    request.session["kensaku"]["irai_type"]=irai_type
    request.session["kensaku"]["tantou"]=tantou
    request.session["kensaku"]["nouhin_com"]=nouhin_com
    request.session["kensaku"]["nouhin_cus"]=nouhin_cus
    request.session["kensaku"]["status"]=status
    request.session["kensaku"]["tel"]=tel
    request.session["kensaku"]["mail"]=mail
    request.session["page_num"]=1

    return redirect("zaiko:irai_rireki")


def rireki_kensaku_all(request):
    request.session["kensaku"]["irai_num"]=""
    request.session["kensaku"]["rental_day_st"]=""
    request.session["kensaku"]["rental_day_ed"]=""
    request.session["kensaku"]["irai_type"]=""
    request.session["kensaku"]["tantou"]=""
    request.session["kensaku"]["nouhin_com"]=""
    request.session["kensaku"]["nouhin_cus"]=""
    request.session["kensaku"]["status"]=""
    request.session["kensaku"]["tel"]=""
    request.session["kensaku"]["mail"]=""
    request.session["page_num"]=1
    return redirect("zaiko:irai_rireki")


def page_prev(request):
    num=request.session["page_num"]
    if num-1 > 0:
        request.session["page_num"] = num - 1
    return redirect("zaiko:irai_rireki")


def page_first(request):
    request.session["page_num"] = 1
    return redirect("zaiko:irai_rireki")


def page_next(request):
    num=request.session["page_num"]
    all_num=request.session["all_page_num"]
    if num+1 <= all_num:
        request.session["page_num"] = num + 1
    return redirect("zaiko:irai_rireki")


def page_last(request):
    all_num=request.session["all_page_num"]
    request.session["page_num"]=all_num
    return redirect("zaiko:irai_rireki")


def csv_imp_page(request):
    return render(request,"zaiko/csv_imp.html")


def dele(request):
    Shouhin.objects.all().delete()
    return render(request,"zaiko/csv_imp.html")


#品番検索に入力
def hinban_enter_ajax(request):
    hinban=request.POST.get("hinban")
    if len(hinban)==0:
        shouhin_list=[]
    else:
        items=Shouhin.objects.filter(~Q(sample_num=""),shouhin_num__contains = hinban ,status=0)
        shouhin_list=[]
        for item in items:
            if item.shouhin_num not in shouhin_list:
                shouhin_list.append(item.shouhin_num)
        shouhin_list.sort()
    d={"hinban":shouhin_list}
    return JsonResponse(d)


#品番リストをクリック（リストボックス）
def hinban_click_ajax(request):
    hinban=request.POST.get("hinban")
    request.session["hinban"]=hinban
    items=Shouhin.objects.filter(~Q(sample_num=""),shouhin_num = hinban,status=0).order_by("size_num")
    color_list=[]
    size_list=[]
    for item in items:
        shouhin_name=item.shouhin_name
        brand=item.brand
        if item.color not in color_list:
            color_list.append(item.color)
        if item.size not in size_list:
            size_list.append(item.size)
    color_list.sort()
    d={
        "color":color_list,
        "size":size_list,
        "shouhin_name":shouhin_name,
        "brand":brand,
    }
    return JsonResponse(d)


#品番リストをクリック（商品一覧）
def hinban_click_ajax2(request):
    hinban=request.session["hinban"]

new_sample/zaiko/templates/zaiko/csv_imp.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DB取込</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <div style="width: 500px;">
        <form action="{% url 'zaiko:csv_imp' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <label for="csv1">在庫リスト：</label>
            <input class="form-control" type="file" name="csv1" id="csv1">
            <br>
            <label for="csv2">貸出リスト：</label>
            <input class="form-control" type="file" name="csv2" id="csv2">
            <br>
            <label for="csv3">サイズリスト：</label>
            <input class="form-control" type="file" name="csv3" id="csv3">
            <br>
            <label for="csv3">カテゴリリスト：</label>
            <input class="form-control" type="file" name="csv4" id="csv4">
            <br>
            <input type="submit" name="btn_upload" value="取込">
            <span style="color: red;">　{{message}}</span>
        </form>
    </div>

</body>
</html>

new_sample/zaiko/templates/zaiko/menu.html
{% load static %}
<!-- メニュー -->
<div class="menu">

    <!-- 依頼側 -->
    <div>
        <a href="https://www.p1-intl.com/" target="_blank"><img src="{% static 'logo.png' %}"></a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko:index' %}"><button type="button" class="btn btn-outline-success">サンプル在庫表</button></a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko:irai_rireki' %}"><button type="button" class="btn btn-outline-success">履歴一覧（修正 / キャンセル）</button></a>
    </div>

    <!-- 管理側 -->
    {% if kanri == 1 %}
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko2:index2' %}"><button type="button" class="btn btn-outline-primary">商品登録 / 編集</button></a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko2:size_category' %}"><button type="button" class="btn btn-outline-primary">カテゴリ / サイズ</button></a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'zaiko2:henkyaku' %}"><button type="button" class="btn btn-outline-primary">返却処理</button></a>
    </div>
    <div style="margin-left: 30px;">
        <a href="{% url 'admin:index' %}" target="_blank"><button type="button" class="btn btn-outline-danger">DB</button></a>
    </div>
    {% endif %}
    
</div>

new_sample/zaiko/templates/zaiko/shouhin_all.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>商品一覧</title>
</head>
<body>
    <div id="shouhin_all">

        <!-- 商品リスト -->
        <div class="mt-1">
        {% for item in items %}

            {% if item.joutai == 0 %}
                <div class='main0 flex hover1'>
                    <div style='width:100px;'>No.{{item.sample_num}}</div>
                    <div style='width:150px; padding-left:20px'></div>
                    <div style='width:250px;'>{{item.color}}</div>
                    <div style='width:100px;'>{{item.size}}</div>
                    <div style='width:250px;'>{{item.kakou}}</div>
                    <div style='width:150px;'>{{item.bikou}}</div>
                    <div style='width:50px; text-align: center;'>
                        <input type='checkbox' class='form-check-input' id='check_add' style='border-color: #646565' name={{item.hontai_num}}>
                    </div>
                </div>
            {% elif item.joutai == 1 %}
                <div class='main1 flex hover1'>
                    <div style='width:100px;'>No.{{item.sample_num}}</div>
                    <div style='width:150px; padding-left:20px'>
                        {% for ren in items2 %}
                            {% if item.irai_num == ren.irai_num_rental %}
                            <div class='joutai1' title='■担当者：{{ren.busho}}　{{ren.tantou}}　　■貸出日：{{ren.rental_day}}　　■お客様：{{ren.com_name}}  {{ren.cus_name}}'>貸出中</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div style='width:250px;'>{{item.color}}</div>
                    <div style='width:100px;'>{{item.size}}</div>
                    <div style='width:250px;'>{{item.kakou}}</div>
                    <div style='width:150px;'>{{item.bikou}}</div>
                    <div style='width:50px; text-align: center;'></div>
                </div>
            {% elif item.joutai == 2 %}
                <div class='main2 flex hover1'>
                    <div style='width:100px;'>No.{{item.sample_num}}</div>
                    <div style='width:150px; padding-left:20px'>
                        {% for ren in items2 %}
                            {% if item.irai_num == ren.irai_num_rental %}
                            <div class='joutai2' title='■担当者：{{ren.busho}}　{{ren.tantou}}　　■キープ日：{{ren.rental_day}}　　■お客様：{{ren.com_name}}  {{ren.cus_name}}'>キープ中</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div style='width:250px;'>{{item.color}}</div>
                    <div style='width:100px;'>{{item.size}}</div>
                    <div style='width:250px;'>{{item.kakou}}</div>
                    <div style='width:150px;'>{{item.bikou}}</div>
                    <div style='width:50px; text-align: center;'>
                        {% for ren in items2 %}
                            {% if item.irai_num == ren.irai_num_rental %}
                            <button type='button' class='btn btn-outline-success btn-sm' style='padding: 0px 5px;' name='{{item.hontai_num}},{{item.irai_num}},{{ren.busho}}　{{ren.tantou}}' id='kaijo'>解除</button>                   
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

        {% endfor %}
        </div>
    </div>


    <!-- 各種Ajax -->
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i <cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
  
        var csrftoken = getCookie('csrftoken');
  
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
  
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
  
        // キープ解除
        kaijo()
        function kaijo(){
            var kaijo=document.querySelectorAll("#kaijo");
            for (var i=0; i<kaijo.length; i++){
                kaijo[i].addEventListener("click",function(){
                    var arr=this.name.split(",");
                    var result = window.confirm(arr[2] + "さんがキープしています。\n\n本当に解除しますか？");
                    if (result){
                        $.ajax({
                            'url': '{% url "zaiko:keep_kaijo_ajax" %}',
                            'type': 'POST',
                            'data': {
                                "hontai_num":arr[0],
                                "irai_num":arr[1],
                            },
                            'dataType': 'json'
                        })
                        .done(function(response){         
                            window.location.reload();
                        })
                    }
                },false)
            }
        }     

        // 依頼リストに追加ボタン
        check_add()
        function check_add(){
            var check_add=document.querySelectorAll("#check_add");
            var ans;
            if (check_add.length > 0) {
                for (var i=0; i<check_add.length; i++){
                    check_add[i].addEventListener("click",function(){
                        if (this.checked){
                            ans="yes";
                        } else {
                            ans="no";
                        };
                        var hontai_num=this.name;
                        $.ajax({
                            'url': '{% url "zaiko:check_addlist_ajax" %}',
                            'type': 'POST',
                            'data': {"ans":ans,"hontai_num":hontai_num},
                            'dataType': 'json'
                        })
                    },false)
                };
            }
        }

    </script>

</body>
</html>


                

new_sample/zaiko/templates/zaiko/unsou_page.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>発送完了CSV取込</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <div style="width: 500px;">
        <form action="{% url 'zaiko:unsou_csv_imp' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <label for="csv1">発送完了CSV:</label>
            <input class="form-control" type="file" name="csv1" id="csv1">
            <br>
            <input type="submit" name="btn_upload" value="取込">
            <span style="color: red;">　{{message}}</span>
        </form>
    </div>
</body>
</html>