new_sample/new_sample/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("zaiko.urls")),
    path('zaiko2/',include("zaiko2.urls")),
]

new_sample/zaiko/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index,shouhin_all,csv_imp,csv_imp_page,dele,hinban_enter_ajax,hinban_click_ajax,color_size_click_ajax,\
                    kakou_click_ajax,swatch_click_ajax,keep_kaijo_ajax,check_addlist_ajax,irai_del_ajax,irai_num_copy,\
                    hinban_click_ajax2,color_size_click_ajax2,toriyose_add_ajax,last_kakunin,\
                    haisou_cus_success,haisou_tempo_success,haisou_keep_success,irai_success,irai_rireki,irai_shusei_ajax,irai_shusei_index,irai_shusei,\
                    rireki_kakunin,page_prev,page_first,page_next,page_last,rireki_kensaku,rireki_kensaku_all,cancel_ajax,keep_hassou,\
                    csv_make,csv_download,unsou_page,unsou_csv_imp,all_delete,eigyou_csv_download


app_name="zaiko"
urlpatterns = [
    path('', index, name="index"),
    path('login/', auth_views.LoginView.as_view(template_name='zaiko/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('shouhin_all/', shouhin_all, name="shouhin_all"), 
    path('irai_success/', irai_success, name="irai_success"), 
    path('irai_rireki/', irai_rireki, name="irai_rireki"), 
    path('irai_shusei_ajax/', irai_shusei_ajax, name="irai_shusei_ajax"), 
    path('irai_shusei_index/', irai_shusei_index, name="irai_shusei_index"), 
    path('irai_shusei/', irai_shusei, name="irai_shusei"), 
    path('rireki_kensaku/', rireki_kensaku, name="rireki_kensaku"),
    path('rireki_kensaku_all/', rireki_kensaku_all, name="rireki_kensaku_all"), 
    path('page_prev/', page_prev, name="page_prev"), 
    path('page_first/', page_first, name="page_first"),
    path('page_next/', page_next, name="page_next"), 
    path('page_last/', page_last, name="page_last"), 
    path('csv_imp_page/', csv_imp_page, name="csv_imp_page"), 
    path('csv_imp/', csv_imp, name="csv_imp"),
    path('dele/', dele, name="dele"), 
    path('hinban_enter_ajax/', hinban_enter_ajax, name="hinban_enter_ajax"),
    path('hinban_click_ajax/', hinban_click_ajax, name="hinban_click_ajax"),
    path('color_size_click_ajax/', color_size_click_ajax, name="color_size_click_ajax"),
    path('kakou_click_ajax/', kakou_click_ajax, name="kakou_click_ajax"),
    path('swatch_click_ajax/', swatch_click_ajax, name="swatch_click_ajax"),
    path('keep_kaijo_ajax/', keep_kaijo_ajax, name="keep_kaijo_ajax"),
    path('check_addlist_ajax/', check_addlist_ajax, name="check_addlist_ajax"),
    path('irai_del_ajax/', irai_del_ajax, name="irai_del_ajax"),
    path('irai_num_copy/', irai_num_copy, name="irai_num_copy"),
    path('hinban_click_ajax2/', hinban_click_ajax2, name="hinban_click_ajax2"),
    path('color_size_click_ajax2/', color_size_click_ajax2, name="color_size_click_ajax2"),
    path('toriyose_add_ajax/', toriyose_add_ajax, name="toriyose_add_ajax"),
    path('last_kakunin/', last_kakunin, name="last_kakunin"),
    path('haisou_cus_success/', haisou_cus_success, name="haisou_cus_success"),
    path('haisou_tempo_success/', haisou_tempo_success, name="haisou_tempo_success"),
    path('haisou_keep_success/', haisou_keep_success, name="haisou_keep_success"),
    path('rireki_kakunin/<int:pk>', rireki_kakunin, name="rireki_kakunin"),
    path('cancel_ajax/', cancel_ajax, name="cancel_ajax"),
    path('keep_hassou/', keep_hassou, name="keep_hassou"),
    path('csv_make/', csv_make, name="csv_make"),
    path('csv_download/', csv_download, name="csv_download"),
    path('unsou_page/', unsou_page, name="unsou_page"),
    path('unsou_csv_imp/', unsou_csv_imp, name="unsou_csv_imp"),
    path('all_delete/', all_delete, name="all_delete"),
    path('eigyou_csv_download/', eigyou_csv_download, name="eigyou_csv_download")
]

new_sample/zaiko2/urls.py
from django.urls import path
from .views import index2,category_click_ajax,hinban_click_ajax,list_click_ajax,ikkatsu_hinban,ikkatsu_del,sample_num_auto,\
                    kobetsu_del,kobetsu_up,label_add,label_print,label_del,henkyaku,henkyaku_kensaku,henkyaku_del,henkyaku_all,henkyaku_csv,henkyaku_spread,\
                    size_category,size_num,size_name,size_new,category_num,category_name,category_new,shouhin_csv_download

app_name="zaiko2"
urlpatterns = [
    path('index2/', index2, name="index2"),
    path('category_click_ajax/', category_click_ajax, name="category_click_ajax"),
    path('hinban_click_ajax/', hinban_click_ajax, name="hinban_click_ajax"),
    path('list_click_ajax/', list_click_ajax, name="list_click_ajax"),
    path('ikkatsu_hinban/', ikkatsu_hinban, name="ikkatsu_hinban"),
    path('ikkatsu_del/', ikkatsu_del, name="ikkatsu_del"),
    path('sample_num_auto/', sample_num_auto, name="sample_num_auto"),
    path('kobetsu_del/', kobetsu_del, name="kobetsu_del"),
    path('kobetsu_up/', kobetsu_up, name="kobetsu_up"),
    path('label_add/', label_add, name="label_add"),
    path('label_print/', label_print, name="label_print"),
    path('label_del/', label_del, name="label_del"),
    path('henkyaku/', henkyaku, name="henkyaku"),
    path('henkyaku_kensaku/', henkyaku_kensaku, name="henkyaku_kensaku"),
    path('henkyaku_del/', henkyaku_del, name="henkyaku_del"),
    path('henkyaku_all/', henkyaku_all, name="henkyaku_all"),
    path('henkyaku_csv/', henkyaku_csv, name="henkyaku_csv"),
    path('henkyaku_spread/', henkyaku_spread, name="henkyaku_spread"),
    path('size_category/', size_category, name="size_category"),
    path('size_num/', size_num, name="size_num"),
    path('size_name/', size_name, name="size_name"),
    path('size_new/', size_new, name="size_new"),
    path('category_num/', category_num, name="category_num"),
    path('category_name/', category_name, name="category_name"),
    path('category_new/', category_new, name="category_new"),
    path('shouhin_csv_download/', shouhin_csv_download, name="shouhin_csv_download"),
]

new_sample/zaiko2/models.py
from django.db import models

# Create your models here.

new_sample/zaiko2/views.py
from django.shortcuts import render,redirect
from zaiko.models import Size,Shouhin,Category,Rental,Label,Rireki_rental,Rireki_shouhin
from django.http import JsonResponse
import json
from django.db.models import Max
from django.contrib.auth.decorators import login_required
import datetime
import csv
from django.http import HttpResponse
import urllib.parse
import requests


@login_required
def index2(request):
    comment=request.session["comment"]
    size_cnt=Size.objects.filter(size_num=0).count()
    #user認証
    kanri=0
    if request.user.username == "p1masao":
        kanri=1
    params={
        "ins":Category.objects.all().order_by("category_num"),
        "sizes":Size.objects.all().order_by("size_num"),
        "label":Label.objects.all().count(),
        "comment":comment,
        "kanri":kanri,
        "size_cnt":size_cnt,
    }
    return render(request,"zaiko2/index2.html",params)


# カテゴリクリック
def category_click_ajax(request):
    category=request.POST.get("category")
    if category == "取寄せ":
        items=list(Shouhin.objects.filter(sample_num = "", status=0).values())
        hinban=Shouhin.objects.filter(sample_num = "", status=0)
    else:
        items=list(Shouhin.objects.filter(category=category, status=0).values())
        hinban=Shouhin.objects.filter(category=category, status=0)
    hinban_list=[]
    for i in hinban:
        if i.shouhin_num not in hinban_list:
            hinban_list.append(i.shouhin_num)
    d={"hinban_list":hinban_list,"items":items}
    return JsonResponse(d)


# 品番クリック
def hinban_click_ajax(request):
    category=request.POST.get("category")
    hinban=request.POST.get("hinban")
    if  category == "取寄せ":
        shouhin_name=Shouhin.objects.filter(shouhin_num=hinban,sample_num="").first().shouhin_name
        items=list(Shouhin.objects.filter(shouhin_num=hinban,sample_num="").values())
    else:
        shouhin_name=Shouhin.objects.filter(shouhin_num=hinban,category=category).first().shouhin_name
        items=list(Shouhin.objects.filter(shouhin_num=hinban, category=category, status=0).values())
    d={"hinban":hinban,"shouhin_name":shouhin_name,"items":items}
    return JsonResponse(d)


# 一括品名更新
def ikkatsu_hinban(request):
    hinban=request.POST["hinban_all"]
    hinmei=request.POST["hinban_all_name"]
    items=Shouhin.objects.filter(shouhin_num=hinban)
    for i in items:
        i.shouhin_name=hinmei
        i.save()
    request.session["comment"]="【一括更新】 商品番号：" + hinban + " の商品名をすべて変更しました！"
    return redirect("zaiko2:index2")


# 一括品番削除（無効）
def ikkatsu_del(request):
    hinban=request.POST["hinban_all"]
    items=Shouhin.objects.filter(shouhin_num=hinban)
    for i in items:
        i.status=1
        i.save()
    for i in items:
        if i.joutai==1:
            irai=Shouhin.objects.filter(irai_num=i.irai_num, status=0).count()
            if irai == 0:
                Rental.objects.get(irai_num_rental=i.irai_num).delete()
    request.session["comment"]="【一括削除】 商品番号：" + hinban + " のサンプルをすべて削除しました！"
    return redirect("zaiko2:index2")


# リストクリック
def list_click_ajax(request):
    hontai_num=request.POST["hontai_num"]
    item=list(Shouhin.objects.filter(hontai_num=hontai_num).values())
    d={"item":item}
    return JsonResponse(d)


# サンプル番号取得
def sample_num_auto(request):
    category=request.POST.get("category")
    if category=="":
        sample_num="no_cate"
    else:
        items=Shouhin.objects.filter(category=category) #model.pyでself.sample_numなのでサンプルNoのみ返ってくる
        if items.count() == 0:
            sample_num="no_get"
        else:
            front=str(items.first()).split("-")[0]
            back_list=[]
            for i in items:
                back_num=str(i).split("-")[1]
                back_num=back_num.replace("★","")
                back_list.append(back_num)
            back_list=list(map(int,back_list))
            for i in range(1,max(back_list)+2):
                if i not in back_list:
                    back=i
                    break
            sample_num=front + "-" + str(back)
    d={"sample_num":sample_num}
    return JsonResponse(d)


# 個別削除（無効）
def kobetsu_del(request):
    hontai_num=request.POST["h_hontai_num"]
    item=Shouhin.objects.get(hontai_num=hontai_num)
    item.status=1
    item.save()
    if item.joutai==1:
        irai=Shouhin.objects.filter(irai_num=item.irai_num, status=0).count()
        if irai == 0:
            Rental.objects.get(irai_num_rental=item.irai_num).delete()
    request.session["comment"]="【個別削除】 サンプルNo." + item.sample_num + " を削除しました！"
    return redirect("zaiko2:index2")


# 個別更新
def kobetsu_up(request):
    hontai_num=request.POST["h_hontai_num"]
    sample_num=request.POST["h_sample_num"]
    sample_num_moto=request.POST["h_sample_num_moto"]
    category=request.POST["h_category"]
    shouhin_num=request.POST["h_shouhin_num"]
    brand=request.POST["h_brand"]
    color=request.POST["h_color"]
    size=request.POST["h_size"]
    shouhin_name=request.POST["h_shouhin_name"]
    kakou=request.POST["h_kakou"]
    bikou=request.POST["h_bikou"]
    touroku_day=request.POST["h_touroku_day"]
    # 新規（コピーから作成）
    if hontai_num == "":
        size_num=Size.objects.get(size=size).size_num
        Shouhin.objects.create(
            sample_num=sample_num,
            category=category,
            shouhin_num=shouhin_num,
            brand=brand,
            shouhin_name=shouhin_name,
            color=color,
            size=size,
            size_num=size_num,
            kakou=kakou,
            bikou=bikou,
        )
        Label.objects.create(
            sample_num=sample_num,
            shouhin_num=shouhin_num,
            shouhin_name=shouhin_name,
            color=color,
            size=size
        )
        comment="【新規登録】 サンプルNo." + sample_num + " を登録しました！"
    # 更新
    else:
        size_num=Size.objects.get(size=size).size_num
        item=Shouhin.objects.get(hontai_num=hontai_num)
        item.sample_num=sample_num
        item.category=category
        item.shouhin_num=shouhin_num
        item.brand=brand
        item.shouhin_name=shouhin_name
        item.color=color
        item.size=size
        item.size_num=size_num
        item.kakou=kakou
        item.bikou=bikou
        item.touroku_day=touroku_day
        item.save()
        comment="【内容更新】 サンプルNo." + sample_num + " の情報を更新しました！"

        if sample_num_moto == "": # 取り寄せ
            Label.objects.create(
                sample_num=sample_num,
                shouhin_num=shouhin_num,
                shouhin_name=shouhin_name,
                color=color,
                size=size,
            )
            comment="【新規登録】 取り寄せ商品（サンプルNo." + sample_num + "）を カテゴリ：" + category + " に登録しました！"
    request.session["comment"]=comment
    return redirect("zaiko2:index2")


# ラベル一覧に追加
def label_add(request):
    sample_num=request.POST.get("sample_num")
    item=Shouhin.objects.filter(sample_num=sample_num)
    for i in item:
        if i.status==0:
            Label.objects.create(
                sample_num=i.sample_num,
                shouhin_num=i.shouhin_num,
                shouhin_name=i.shouhin_name,
                color=i.color,
                size=i.size,
            )
            break
    d={"":""}
    return JsonResponse(d)


# ラベル一覧
def label_print(request):
    items=Label.objects.all()
    if items.count() > 16:
        items1=items[:8]
        items2=items[7:16]
        items3=items[15:]
        params={"items1":items1,"items2":items2,"items3":items3,"col":3}

    elif items.count() >8:
        items1=items[:8]
        items2=items[8:16]
        params={"items1":items1,"items2":items2,"col":2}

    else:
        items1=items[:8]
        params={"items1":items1,"col":1}

    #user認証
    kanri=0
    if request.user.username == "p1masao":
        kanri=1
    params["kanri"]=kanri

    return render(request,"zaiko2/label.html",params)


# ラベル消去
def label_del(request):
    Label.objects.all().delete()
    return redirect("zaiko2:label_print")


@login_required
def henkyaku(request):
    if "henkyaku" not in request.session:
        request.session["henkyaku"]={}
    if "msg" not in request.session["henkyaku"]:
        request.session["henkyaku"]["msg"]=""
    if "items" not in request.session["henkyaku"]:
        request.session["henkyaku"]["items"]=""

    msg=request.session["henkyaku"]["msg"]
    item_list=request.session["henkyaku"]["items"]
    items=Shouhin.objects.filter(hontai_num__in=item_list)
    #user認証
    kanri=0
    if request.user.username == "p1masao":
        kanri=1

    return render(request,"zaiko2/henkyaku.html",{"msg":msg,"items":items,"kanri":kanri})


# 返却検索
def henkyaku_kensaku(request):
    sample_num=request.POST["sample_num"]
    irai_num=request.POST["irai_num"]
    msg=""
    items=""
    if sample_num != "":
        try:
            irai_num2=Shouhin.objects.get(sample_num=sample_num).irai_num
            if irai_num2 == 0:
                msg="サンプルNo." + sample_num +  " は貸出中ではありません。"
            else:
                items=list(Shouhin.objects.filter(irai_num=irai_num2).values_list("hontai_num",flat=True))
        except:
            msg="サンプルNo." + sample_num +  " は存在しません。"
            items=""
    if irai_num != "":
        try:
            items=list(Shouhin.objects.filter(irai_num=irai_num).values_list("hontai_num",flat=True))
            irai_max=Rireki_rental.objects.all().aggregate(Max("irai_num"))
            irai_max=irai_max['irai_num__max']
            if int(irai_num) > irai_max:
                msg="依頼No." + str(irai_num) +  " は存在しません。"
            elif len(items) == 0:
                msg="依頼No." + str(irai_num) +  " はすでに返却されているか、存在しません。"
        except:
            msg="依頼No." + str(irai_num) +  " は存在しません。"

    request.session["henkyaku"]["msg"]=msg
    request.session["henkyaku"]["items"]=items
    return redirect("zaiko2:henkyaku")


# 返却リストから削除
def henkyaku_del(request):
    hen_del=request.POST.get("hen_del")
    items=request.session["henkyaku"]["items"]

new_sample/zaiko2/templates/zaiko2/henkyaku.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="icon" href="{% static 'tamori.gif' %}">
    <title>サンプル在庫_管理（返却）</title>
</head>
<body>
    <div class="container mt-3 mb-5">
        <div style="margin: 0 auto; justify-content: center; width: 1100px;">

            <!-- メニュー -->
            {% include "zaiko/menu.html" with kanri=kanri %}

            <div class="flex4" style="margin-top: 50px;">
                <div>
                    <form action="{% url 'zaiko2:henkyaku_kensaku' %}" method="post">{% csrf_token %}
                        <div class="flex2">
                            <div>サンプルNo.：</div>
                            <div><input class="form-control" id="sample_num" name="sample_num" type="text" style="width: 150px;"></div>
                            <div style="margin-left: 30px;">依頼No.：</div>
                            <div><input class="form-control" id="irai_num" name="irai_num" type="text" style="width: 150px;"></div>
                            <div style="margin-left: 30px;"><button class="btn btn-secondary" type="submit">検索</button></div>
                        </div>
                    </form>
                </div>
                <div class="flex" style="margin: auto 0;">
                    <div>
                        <div>
                            <a href="{% url 'zaiko2:henkyaku_spread' %}"><button class="btn btn-outline-dark"><i class="bi bi-arrow-repeat"></i> 未返却をスプシへ反映</button></a>
                        </div>
                        {% if ans %}
                        <div style="color: red;">完了しました！</div>
                        {% endif %}
                    </div>
                    <div style="margin-left: 50px;">
                        <a href="{% url 'zaiko2:henkyaku_csv' %}"><button class="btn btn-outline-dark"><i class="bi bi-download"></i> 未返却を抽出</button></a>
                    </div>
                </div>
            </div>
            
            <div class="mt-3">
                {% if msg != "" %}
                    <span style="font-size: 1.3em; color: red;">{{msg}}</span>
                {% else %}
                    <div>
                        <table class="table table-bordered" style="width: 1100px;">
                            <thead>
                                <tr class="table-secondary">
                                    <th>依頼No.</th>
                                    <th>サンプルNo.</th>
                                    <th>商品番号</th>
                                    <th>ブランド</th>
                                    <th>商品名</th>
                                    <th>カラー</th>
                                    <th>サイズ</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in items %}
                                <tr>
                                    <td style="vertical-align: middle;">{{i.irai_num}}</td>
                                    <td style="vertical-align: middle;">{{i.sample_num}}</td>
                                    <td style="vertical-align: middle;">{{i.shouhin_num}}</td>
                                    <td style="vertical-align: middle;">{{i.brand}}</td>
                                    <td style="vertical-align: middle;">{{i.shouhin_name}}</td>
                                    <td style="vertical-align: middle;">{{i.color}}</td>
                                    <td style="vertical-align: middle;">{{i.size}}</td>
                                    <td style="text-align: center;">
                                        <button type="button" class="btn btn-outline-dark btn-sm" id="henkyaku_del" name={{i.hontai_num}}>
                                            <i class="bi bi-x-lg"></i>
                                        </button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-4" style="width: 100%; text-align: right";>
                        <button class="btn btn-primary" id="henkyaku_all" type="submit">一括返却処理</button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i <cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
  
        var csrftoken = getCookie('csrftoken');
  
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
  
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        

        // 依頼Noの削除
        document.getElementById("sample_num").addEventListener("input",function(){
            document.getElementById("irai_num").value="";
        })

        // サンプルNoの削除
        document.getElementById("irai_num").addEventListener("input",function(){
            document.getElementById("sample_num").value="";
        })

        // 一覧から削除
        henkyaku_del()
        function henkyaku_del(){
            var hen=document.querySelectorAll("#henkyaku_del");
            for (var i=0; i<hen.length; i++){
                hen[i].addEventListener("click",function(){
                    $.ajax({
                        'url': '{% url "zaiko2:henkyaku_del" %}',
                        'type': 'POST',
                        'data': {"hen_del":this.name},
                        'dataType': 'json'
                    })
                    .done(function(response){                
                        window.location.reload();
                    })
                },false)
            }
        }

        // 一括返却
        document.getElementById("henkyaku_all").addEventListener("click",function(){
            $.ajax({
                'url': '{% url "zaiko2:henkyaku_all" %}',
                'type': 'POST',
            })
            .done(function(response){                
                window.location.reload();
                window.alert("一括返却処理が完了しました！");
            })
        })

    </script>
</body>
</html>

new_sample/zaiko2/templates/zaiko2/label.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="icon" href="{% static 'tamori.gif' %}">
    <title>サンプル在庫_管理（ラベル印刷）</title>

    <style>
        table, td, th {
            border: 1px #000000 solid;
            font-size:auto;
        }
    </style>
</head>
<body>
    <div class="container mt-3 mb-5">
        <div style="margin: 0 auto; justify-content: center; width: 1100px;">

            <!-- メニュー -->
            {% include "zaiko/menu.html" with kanri=kanri %}

            <div class="flex2" style="margin-top: 50px;">
                <div><button type="button" class="btn btn-secondary" id="print"><i class="bi bi-printer-fill"></i> 印刷</button></div>
                <div style="margin-left: 50px;">
                    <a href="{% url 'zaiko2:label_del' %}">
                        <button type="button" class="btn btn-outline-danger" onclick="return confirm('本当に消去しますか？')" >データを消去する</button>
                    </a>
                </div>
            </div>

            <div class="flex_print mt-4">
                <!-- １列目 -->
                <div>
                    <div style="width:310px; display: inline;">
                        {% for i in items1 %}
                        <table style="width:300px;margin: 5px;border: #000000 2px solid;">
                            <tr><td style="width: 20%; height: 43px; text-align: center;">No.</td><td style="width: 80%;font-weight: bold;font-size: 1.5em;padding-left: 5px;">{{i.sample_num}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">品番</td><td style="padding-left: 5px;">{{i.shouhin_num}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">品名</td><td style="padding-left: 5px;">{{i.shouhin_name}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">カラー</td><td style="padding-left: 5px;">{{i.color}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;;">サイズ</td><td style="padding-left: 5px;">{{i.size}}</td></tr>
                        </table>
                        {% endfor %}
                    </div>
                </div>
                <!-- 2列目 -->
                <div>
                    <div style="width:310px; display: inline;">
                        {% for i in items2 %}
                        <table style="width:300px;margin: 5px;border: #000000 2px solid;">
                            <tr><td style="width: 20%; height: 43px; text-align: center;">No.</td><td style="width: 80%;font-weight: bold;font-size: 1.5em;padding-left: 5px;">{{i.sample_num}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">品番</td><td style="padding-left: 5px;">{{i.shouhin_num}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">品名</td><td style="padding-left: 5px;">{{i.shouhin_name}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">カラー</td><td style="padding-left: 5px;">{{i.color}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;;">サイズ</td><td style="padding-left: 5px;">{{i.size}}</td></tr>
                        </table>
                        {% endfor %}
                    </div>
                </div>
                <!-- 3列目 -->
                <div>
                    <div style="width:310px; display: inline;">
                        {% for i in items3 %}
                        <table style="width:300px;margin: 5px;border: #000000 2px solid;">
                            <tr><td style="width: 20%; height: 43px; text-align: center;">No.</td><td style="width: 80%;font-weight: bold;font-size: 1.5em;padding-left: 5px;">{{i.sample_num}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">品番</td><td style="padding-left: 5px;">{{i.shouhin_num}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">品名</td><td style="padding-left: 5px;">{{i.shouhin_name}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;">カラー</td><td style="padding-left: 5px;">{{i.color}}</td></tr>
                            <tr><td style="height: 28px;text-align: center;;">サイズ</td><td style="padding-left: 5px;">{{i.size}}</td></tr>
                        </table>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script>
        document.getElementById("print").addEventListener("click",function(){
            window.print();
        })
    </script>
</body>
</html>